### ISSUE TITLE
flymake-mode not started using snippet in README

### ISSUE THREAD

**Issue by jcubic** [emacs-languagetool/flymake-languagetool#21]
The documentation doesn't say that you need to run:

```lips
(flymake-mode)
```

It seems the mode is not enabled by default when calling `(flymake-languagetool-load)`

**Comment by jcs090218** [comment]
Yes, you will still need to enable `flymake-mode` after `(flymake-language-tool-load)`. Flymake is the frontend and can work with multiple checkers so it wasn't included as a part of the documentation.

I'm no longer an Emacs beginner, so I don't know what documentation is required. PRs for improving documentation are always welcome. :)

**Comment by tpeacock19** [comment]
Even though step 4 explicitly says to call `flymake-mode`, the following step is offered as an alternative without any mention of the mode.

I'll update readme to be a bit clearer.

**Comment by tpeacock19** [comment]
I understand the desire to have a snippet you can copy and paste. However, I won't be adding any calls to `flymake-mode` in the snippets since it is a minor-mode and the expectation is if someone is installing a diagnostic for flymake they know how to enable it. For more information on flymake, how it is enabled, and other functionality I suggest reading the `info (C-h i)` documentation.
